---
title: "DeBruin Summary"
author: "Jonathan Bahlmann"
date: '2022-06-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r comment, echo=F, eval=F}
# knit to markdown:
  md_document:
    variant: markdown_github
```

```{r, echo=F, warning=F, message=F}
library(sf)
library(raster)
library(ggplot2)
library(ggpubr)
```

## Sampling Designs
Plotting a randomly chosen sampling design example.

```{r, echo=F}
# par(mfrow=c(3,2))
# gdalwarp -tr 5000 5000 -r average agb.tif agb_resamples.tif
agb <- raster::raster("./data/agb_resampled.tif")
sample_plots <- lapply(list.files("./samples"), function(dir) {
  r <- floor(runif(1, 1, 100))
  # print(paste0(dir, ": plotting the ", r, "th sampling design."))
  samp_name <- paste0("./samples/", dir, "/", sprintf("%03d", r), "_coords", ".Rdata")
  load(samp_name)
  if(class(pts)[1] != "sf") {
    sample_df <- as.data.frame(pts)
    sample_sf <- st_as_sf(sample_df, coords = c("x", "y"))
    st_crs(sample_sf) <- st_crs(agb) # set crs EPSG:3035
  } else {
    sample_sf <- pts
  }
  
  agb_df <- as.data.frame(agb, xy=TRUE)
  
  m1 <- ggplot() + 
    geom_raster(data=agb_df, aes(x=x, y=y, fill=agb_resampled)) + 
    geom_sf(data=sample_sf, shape = 2, size = 0.1) + 
    theme_light() +
    scale_fill_gradientn(colours=terrain.colors(10), na.value="transparent") + #, na.value = "transparent") +
    ggtitle(dir)
  
  return(m1)
}) 

# raster::plot(agb, main = dir)
# plot(sample_sf, add=TRUE, pch=5, cex=0.1, color="black")
```

```{r, fig.width=12, fig.height=8, echo=F}
ggarrange(plotlist=sample_plots,
          ncol=3, nrow=2, common.legend = T)
```

## Recreating Fig. 9

```{r, eval=T}
# ************************************************************************
# ******************************* Figure 9 *******************************
# ************************************************************************
library(openxlsx)

infolder  <- "./CVresults"
outfolder <- "./material"

mets <- c("exhaustive", "random", "spatial", "intensity",
          "modelbased", "heteroscedastic", "nndm")

colnms <- c("method", "variate", "design", "number", "RMSE", "MEC")
outtab <- data.frame(matrix(NA, 0, 10))
names(outtab) <- colnms

for(m in mets){
  p <- file.path(infolder, m)
  f_ins <- list.files(p, glob2rx("???_*.Rdata"))
  for(f_in in f_ins){
    lchar <- nchar(f_in)
    variate <- substr(f_in, 1, 3)
    design <- substr(f_in, 5, lchar-9)
    number <- as.numeric(substr(f_in, lchar-8, lchar-6))
    load(file.path(p, f_in))
    if(m == "modelbased" | m == "heteroscedastic"){
      MEC    <- mean(MECs)
      RMSE   <- mean(RMSEs)
    } else{
      if(length(MEC) > 1){
        MEC  <- mean(MEC)
        RMSE <- mean(RMSE)
      }
    }
    
    newrow <- data.frame(method = m, variate = variate, design = design,
                         number = number, RMSE = RMSE, MEC = MEC)
    outtab <- rbind(outtab, newrow)
  }
}

write.xlsx(outtab, file.path(outfolder, "outtab100.xlsx"), overwrite = T)
```

```{r, eval=T}
ggplot(data=outtab[outtab$variate == "AGB",]) +
  geom_boxplot(aes(x=method, y=RMSE, color=design))
```

```{r, eval=T}
mytab <- outtab[outtab$variate == "AGB",]
# mytab <- mytab[mytab$number < 6,]
mytab$rRMSE <- NA
mytab$rMEC  <- NA

for (design in unique(mytab$design)) {
  for (number in 1:90) {
    measurement <- which(mytab$design == design & mytab$number == number)
    validation <- which(mytab$design == design & mytab$number == number & mytab$method == "exhaustive")
    mytab$rRMSE[measurement] <- 100 * (mytab$RMSE[measurement] - mytab$RMSE[validation])/
        mytab$RMSE[validation]
    mytab$rMEC[measurement] <- 100 * (mytab$MEC[measurement] - mytab$MEC[validation])/
        mytab$MEC[validation]
  }
}

boxplot(rRMSE~method, data=mytab)

mytab$design[mytab$design == "clusterGapped"] <- "e_clusterGapped"
mytab$design[mytab$design == "simpleRandom"] <- "a_simpleRandom"
mytab$design[mytab$design == "regular"] <- "b_regular"
mytab$design[mytab$design == "clusterMedium"] <- "c_clusterMedium"
mytab$design[mytab$design == "clusterStrong"] <- "d_clusterStrong"

mytab$method[mytab$method == "exhaustive"] <- "a_exhaustive"
mytab$method[mytab$method == "random"] <- "b_random"
mytab$method[mytab$method == "spatial"] <- "c_spatial"
mytab$method[mytab$method == "intensity"] <- "d_intensity"
mytab$method[mytab$method == "modelbased"] <- "e_modelbased"
mytab$method[mytab$method == "nndm"] <- "f_nndm"



levels(as.factor(mytab$design))

ggplot(data=mytab) +
  geom_boxplot(aes(x=method, y=rRMSE, color=design))
```


started with CV_exhaustive_parallel [done]
next: maybe try own plot, maybe try to get this running [done]
next: set up palma jobs for all validation techniques 
```{r, eval=F}
# ***************************************************
# ******** PLOTS ACCURACY METRICS CV METHODS ********
# ***************************************************

outtab <- read.xlsx(file.path(outfolder, "outtab100.xlsx"))
outtab$methodID <- with(outtab, ifelse(method == "random", 3, 
                                       ifelse(method == "spatial", 8,
                                       ifelse(method == "intensity", 13,
                                       ifelse(method == "modelbased", 18,
                                       ifelse(method == "heteroscedastic", 23, 
                                       0))))))

# relative RMSE & MEC
outtab$rRMSE <- NA
outtab$rMEC  <- NA
for(variate in c("AGB", "OCS")){
  for(design in unique(outtab$design)){
    for(number in 1:100){
      idx1 <- which(outtab$design == design & outtab$variate == variate & 
                      outtab$number == number)
      idx2 <- which(outtab$design == design & outtab$variate == variate & 
                      outtab$methodID == 0 & outtab$number == number)
      
      outtab$rRMSE[idx1] <- 100 * (outtab$RMSE[idx1] - outtab$RMSE[idx2])/
        outtab$RMSE[idx2]
      outtab$rMEC[idx1] <- 100 * (outtab$MEC[idx1] - outtab$MEC[idx2])/
        outtab$MEC[idx2]
    }
  }
}

idx  <- which(outtab$design ==  "simpleRandom")
outtab$methodID[idx] <- outtab$methodID[idx] - 2

idx  <- which(outtab$design ==  "regular")
outtab$methodID[idx] <- outtab$methodID[idx] - 1

# idx  <- which(outtab$design ==  "clusterMedium")
# outtab$methodID[idx] <- outtab$methodID[idx]

idx  <- which(outtab$design ==  "clusterStrong")
outtab$methodID[idx] <- outtab$methodID[idx] + 1

idx  <- which(outtab$design ==  "clusterGapped")
outtab$methodID[idx] <- outtab$methodID[idx] + 2

xx <- c(1:5, 6:10, 11:15, 16:20, 21:25)


windows(12,8)
par(mfrow=c(2,2), cex.axis=1.1, cex.lab=1.2, mar=c(4.5, 4.5, 1.5, 1))
cols <- rep(c("white", "brown", "pink", "orange", "lightgreen"), 4)

# ******** AGB RMSE ********
boxplot(rRMSE~methodID, data=outtab, 
        subset = which(outtab$variate == "AGB" & outtab$methodID > 0.5),
        xlab="", ylab = "relative RMSE [%]", col=cols, range=0, xaxt="n",
        main = "AGB", boxwex= 0.8, ylim=c(-74, 62))
idx <- which(outtab$variate == "AGB" & outtab$methodID > 0.5)
yy <- aggregate(outtab$rRMSE[idx], 
                by=list(outtab$methodID[idx]), mean)$x
abline(v = c(5.5, 10.5, 15.5, 20.5), lty=3, lwd = 3, col="lightgrey")
abline(h = 0, lty=2, col="red", lwd=2)

points(xx, yy, col="black", bg=cols, lwd=1.5,
       cex=1.2, pch=21)

axis(side=1, at=c(3, 8, 13, 18, 23), cex=1.2,
     labels=c("conventional", "spatial", "weighted", "hom.sced.", 
              "het.sced."))

mtext("(a)", 3, adj = 0, padj = 0, cex=1.15, font=1)


# ******** OCS RMSE ********

boxplot(rRMSE~methodID, data=outtab, 
        subset = which(outtab$variate == "OCS" & outtab$methodID > 0.5),
        xlab="", ylab = "relative RMSE [%]", col=cols, range=0, xaxt="n",
        main = "OCS", boxwex= 0.8, ylim=c(-74, 62))
idx <- which(outtab$variate == "OCS" & outtab$methodID > 0.5)
yy <- aggregate(outtab$rRMSE[idx], 
                by=list(outtab$methodID[idx]), mean)$x
abline(v = c(5.5, 10.5, 15.5, 20.5), lty=3, lwd = 3, col="lightgrey")
abline(h = 0, lty=2, col="red", lwd=2)

points(xx, yy, col="black", bg=cols, lwd=1.5,
       cex=1.2, pch=21)

axis(side=1, at=c(3, 8, 13, 18, 23), cex=1.2,
     labels=c("conventional", "spatial", "weighted", "hom.sced.", 
              "het.sced."))

mtext("(b)", 3, adj = 0, padj = 0, cex=1.15, font=1)

legend("topright", c("SRS", "syst", "clustMed",
                     "clustStr", "clustGap"), fill=cols, 
       cex = 1.1, bg="white")


# ******** AGB MEC ********
boxplot(rMEC~methodID, data=outtab, 
        subset = which(outtab$variate == "AGB" & 
                         outtab$methodID > 0.5),  
        xlab="", ylab = "relative MEC [%]",
        col=cols, range=0, xaxt="n",
        at = xx, main = "AGB",
        boxwex= 0.8, ylim=c(-49,40))
idx <- which(outtab$variate == "AGB" & outtab$methodID > 0.5)
yy <- aggregate(outtab$rMEC[idx], 
                by=list(outtab$methodID[idx]), mean)$x
abline(v = c(5.5, 10.5, 15.5, 20.5), lty=3, lwd = 3, col="lightgrey")
abline(h = 0, lty=2, col="red", lwd=2)

points(xx, yy, col="black", bg=cols, lwd=1.5,
       cex=1.2, pch=21)

axis(side=1, at=c(3, 8, 13, 18, 23), cex=1.2,
     labels=c("conventional", "spatial", "weighted", "hom.sced.", 
              "het.sced."))

mtext("(c)", 3, adj = 0, padj = 0, cex=1.15, font=1)


# ******** OCS MEC ********
boxplot(rMEC~methodID, data=outtab, 
        subset = which(outtab$variate == "OCS" & 
                         outtab$methodID > 0.5),  
        xlab="", ylab = "relative MEC [%]",
        col=cols, range=0, xaxt="n",
        at = xx, main = "OCS",
        boxwex= 0.8, ylim=c(-49,40))
idx <- which(outtab$variate == "OCS" & outtab$methodID > 0.5)
yy <- aggregate(outtab$rMEC[idx], 
                by=list(outtab$methodID[idx]), mean)$x
abline(v = c(5.5, 10.5, 15.5, 20.5), lty=3, lwd = 3, col="lightgrey")
abline(h = 0, lty=2, col="red", lwd=2)

points(xx, yy, col="black", bg=cols, lwd=1.5,
       cex=1.2, pch=21)

axis(side=1, at=c(3, 8, 13, 18, 23), cex=1.2,
     labels=c("conventional", "spatial", "weighted", "hom.sced.", 
              "het.sced."))

mtext("(d)", 3, adj = 0, padj = 0, cex=1.15, font=1)
```

