---
title: "DeBruin Summary"
author: "Jonathan Bahlmann"
date: '2022-06-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r comment, echo=F, eval=F}
# knit to markdown:
  md_document:
    variant: markdown_github
```

```{r, echo=F, warning=F, message=F}
library(sf)
library(raster)
library(ggplot2)
library(ggpubr)
library(openxlsx)
```

## Sampling Designs
As a reminder: Plotting a randomly chosen sampling design example.

```{r, echo=F}
# par(mfrow=c(3,2))
# gdalwarp -tr 5000 5000 -r average agb.tif agb_resamples.tif
agb <- raster::raster("../data/agb_resampled.tif")
plot_sample <- "clusterMedium"
sample_plots <- lapply(list.files("./samples"), function(dir) {
  r <- floor(runif(1, 1, 10))
  # print(paste0(dir, ": plotting the ", r, "th sampling design."))
  samp_name <- paste0("./samples/", dir, "/", plot_sample, "/", sprintf("%03d", r), "_coords", ".Rdata")
  load(samp_name)
  
  agb_df <- as.data.frame(agb, xy=TRUE)
  
  m1 <- ggplot() + 
    geom_raster(data=agb_df, aes(x=x, y=y, fill=agb_resampled)) + 
    geom_sf(data=pts_sf, shape = 2, size = 0.1) + 
    theme_light() +
    scale_fill_gradientn(colours=terrain.colors(10), na.value="transparent") + #, na.value = "transparent") +
    ggtitle(dir)
  
  return(m1)
}) 

# raster::plot(agb, main = dir)
# plot(sample_sf, add=TRUE, pch=5, cex=0.1, color="black")
```

```{r, fig.width=12, fig.height=8, echo=F}
ggarrange(plotlist=sample_plots,
          ncol=3, nrow=2, common.legend = T)
```

## Gather Result Data

Gather data from their output folders into a dataframe.

```{r, eval=T}
infolder <- "./CVresults"
outfolder <- "./material"

colnms <- c("method", "variate", "design", "number", "RMSE")
outtab <- data.frame(matrix(NA, 0, 10))
names(outtab) <- colnms

for(m in c("sampled_700", 
          "sampled_1000")){
  # get exhaustive
  p <- file.path(infolder, "exhaustive", m)
  f_ins <- list.files(p, glob2rx("???_*.Rdata"))
  for(f_in in f_ins){
    lchar <- nchar(f_in)
    variate <- substr(f_in, 1, 3)
    design <- substr(f_in, 5, lchar-9)
    number <- as.numeric(substr(f_in, lchar-8, lchar-6))
    load(file.path(p, f_in))
    if(length(RMSE) > 1) {
      RMSE <- mean(RMSE)
    }
    if(m == "sampled_700") {
      m = "exhaustive_700"
    }
    if(m == "sampled_1000") {
      m = "exhaustive_1000"
    }
    
    newrow <- data.frame(method = m, variate = variate, design = design,
                         number = number, RMSE = RMSE)
    outtab <- rbind(outtab, newrow)
  }
}

# get sampled
for(m in c("nndm_sampled700_samps_1000_mint_0", 
          "nndm_sampled1000_samps_1000_mint_0")){
  # get exhaustive
  p <- file.path(infolder, m)
  f_ins <- list.files(p, glob2rx("???_*.Rdata"))
  for(f_in in f_ins){
    lchar <- nchar(f_in)
    variate <- substr(f_in, 1, 3)
    design <- substr(f_in, 5, lchar-9)
    number <- as.numeric(substr(f_in, lchar-8, lchar-6))
    load(file.path(p, f_in))
    if(length(RMSE) > 1) {
      RMSE <- mean(RMSE)
    }
    if(m == "nndm_sampled700_samps_1000_mint_0") {
      m = "sampled_700"
    }
    if(m == "nndm_sampled1000_samps_1000_mint_0") {
      m = "sampled_1000"
    }
    
    newrow <- data.frame(method = m, variate = variate, design = design,
                         number = number, RMSE = RMSE)
    outtab <- rbind(outtab, newrow)
  }
}

write.xlsx(outtab, file.path(outfolder, "outtab100.xlsx"), overwrite = T)
head(outtab)
```


```{r, eval=T}
ggplot(data=outtab[outtab$variate == "AGB",]) +
  geom_boxplot(aes(x=method, y=RMSE, color=design)) +
  ggtitle("AGB: RMSE by CV Method")

ggplot(data=outtab[outtab$variate == "OCS",]) +
  geom_boxplot(aes(x=method, y=RMSE, color=design)) +
  ggtitle("OCS: RMSE by CV Method")
```

```{r, eval=T}
mytab <- outtab[outtab$variate == "AGB",]
# mytab <- mytab[mytab$number < 6,]
mytab$rRMSE <- NA

for (design in unique(mytab$design)) {
  for (number in 1:10) {
    measurement <- which(mytab$design == design & mytab$number == number & mytab$method == "sampled_700")
    validation <- which(mytab$design == design & mytab$number == number & mytab$method == "exhaustive_700")
    mytab$rRMSE[measurement] <- 100 * (mytab$RMSE[measurement] - mytab$RMSE[validation])/
        mytab$RMSE[validation]
    
    measurement <- which(mytab$design == design & mytab$number == number & mytab$method == "sampled_1000")
    validation <- which(mytab$design == design & mytab$number == number & mytab$method == "exhaustive_1000")
    mytab$rRMSE[measurement] <- 100 * (mytab$RMSE[measurement] - mytab$RMSE[validation])/
        mytab$RMSE[validation]
  }
}

# boxplot(rRMSE~method, data=mytab)

mytab$design[mytab$design == "clusterGapped"] <- "e_clusterGapped"
mytab$design[mytab$design == "simpleRandom"] <- "a_simpleRandom"
mytab$design[mytab$design == "regular"] <- "b_regular"
mytab$design[mytab$design == "clusterMedium"] <- "c_clusterMedium"
mytab$design[mytab$design == "clusterStrong"] <- "d_clusterStrong"

# mytab$design[mytab$method == "sampled_700"] <- "a_sampled_700"
# mytab$design[mytab$design == "sampled_1000"] <- "b_sampled_1000"

levels(as.factor(mytab$design))

ggplot(data=mytab[(mytab$method != "exhaustive_1000" & mytab$method != "exhaustive_700"),]) +
  geom_boxplot(aes(x=method, y=rRMSE, color=design)) +
  ggtitle("AGB: relative RMSE (%) by CV Method")
```

```{r, eval=T}
mytab <- outtab[outtab$variate == "OCS",]
# mytab <- mytab[mytab$number < 6,]
mytab$rRMSE <- NA

for (design in unique(mytab$design)) {
  for (number in 1:10) {
    measurement <- which(mytab$design == design & mytab$number == number & mytab$method == "sampled_700")
    validation <- which(mytab$design == design & mytab$number == number & mytab$method == "exhaustive_700")
    mytab$rRMSE[measurement] <- 100 * (mytab$RMSE[measurement] - mytab$RMSE[validation])/
        mytab$RMSE[validation]
    
    measurement <- which(mytab$design == design & mytab$number == number & mytab$method == "sampled_1000")
    validation <- which(mytab$design == design & mytab$number == number & mytab$method == "exhaustive_1000")
    mytab$rRMSE[measurement] <- 100 * (mytab$RMSE[measurement] - mytab$RMSE[validation])/
        mytab$RMSE[validation]
  }
}

# boxplot(rRMSE~method, data=mytab)

mytab$design[mytab$design == "clusterGapped"] <- "e_clusterGapped"
mytab$design[mytab$design == "simpleRandom"] <- "a_simpleRandom"
mytab$design[mytab$design == "regular"] <- "b_regular"
mytab$design[mytab$design == "clusterMedium"] <- "c_clusterMedium"
mytab$design[mytab$design == "clusterStrong"] <- "d_clusterStrong"

# mytab$design[mytab$method == "sampled_700"] <- "a_sampled_700"
# mytab$design[mytab$design == "sampled_1000"] <- "b_sampled_1000"

levels(as.factor(mytab$design))

ggplot(data=mytab[(mytab$method != "exhaustive_1000" & mytab$method != "exhaustive_700"),]) +
  geom_boxplot(aes(x=method, y=rRMSE, color=design)) +
  ggtitle("OCS: relative RMSE (%) by CV Method")
```

* nndm ohne phi aus CAST paket
